# Dependencies
markdown:         kramdown
highlighter:      pygments
exclude: ["README.md"]

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sean Zimmer
tag_text:         
description:      Personal website of Sean K Zimmer, Naturalist, Brooklyn NY. 
url:              http://seanzimmer.github.io
baseurl:          /
